require 'csv' if RUBY_VERSION > '1.9'
require 'mathn'
require 'rss'
require 'nkf'
require 'ipaddr'
require 'plugins'
require 'enju_root/bookmark_url'
require 'enju_root/calculate_stat'
require 'enju_root/expire_editable_fragment'
require 'enju_root/localized_name'
require 'enju_root/master_model'
require 'enju_root/openurl'
require 'enju_root/porta_cql'
require 'enju_root/sru'
require 'enju_root/version'
